package com.mockuai.shopcenter.domain.dto;

import java.io.Serializable;
import java.util.Date;

public class RItemGroupDTO implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.biz_code
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.seller_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.group_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private Long groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.item_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.delete_mark
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private Byte deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.delete_version
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private Long deleteVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.gmt_created
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_group.gmt_modified
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.id
     *
     * @return the value of r_item_group.id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.id
     *
     * @param id the value for r_item_group.id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.biz_code
     *
     * @return the value of r_item_group.biz_code
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.biz_code
     *
     * @param bizCode the value for r_item_group.biz_code
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.seller_id
     *
     * @return the value of r_item_group.seller_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.seller_id
     *
     * @param sellerId the value for r_item_group.seller_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.group_id
     *
     * @return the value of r_item_group.group_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.group_id
     *
     * @param groupId the value for r_item_group.group_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.item_id
     *
     * @return the value of r_item_group.item_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.item_id
     *
     * @param itemId the value for r_item_group.item_id
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.delete_mark
     *
     * @return the value of r_item_group.delete_mark
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public Byte getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.delete_mark
     *
     * @param deleteMark the value for r_item_group.delete_mark
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setDeleteMark(Byte deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.delete_version
     *
     * @return the value of r_item_group.delete_version
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public Long getDeleteVersion() {
        return deleteVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.delete_version
     *
     * @param deleteVersion the value for r_item_group.delete_version
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setDeleteVersion(Long deleteVersion) {
        this.deleteVersion = deleteVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.gmt_created
     *
     * @return the value of r_item_group.gmt_created
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.gmt_created
     *
     * @param gmtCreated the value for r_item_group.gmt_created
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_group.gmt_modified
     *
     * @return the value of r_item_group.gmt_modified
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_group.gmt_modified
     *
     * @param gmtModified the value for r_item_group.gmt_modified
     *
     * @mbggenerated Wed May 11 10:37:16 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}