package com.mockuai.shopcenter.domain.dto;

import java.io.Serializable;
import java.util.Date;

public class ShopItemDTO implements Serializable{
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.id
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    private Long id;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.shop_id
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    private Long shopId;

    private String itemUid;

    private Long groupId;

    public Long getGroupId() {
        return groupId;
    }

    public void setGroupId(Long groupId) {
        this.groupId = groupId;
    }

    public String getItemUid() {
        return itemUid;
    }

    public void setItemUid(String itemUid) {
        this.itemUid = itemUid;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Long getBrandId() {
        return brandId;
    }

    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    public Long getMarketPrice() {
        return marketPrice;
    }

    public void setMarketPrice(Long marketPrice) {
        this.marketPrice = marketPrice;
    }

    public Long getPromotionPrice() {
        return promotionPrice;
    }

    public void setPromotionPrice(Long promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    public Long getWirelessPrice() {
        return wirelessPrice;
    }

    public void setWirelessPrice(Long wirelessPrice) {
        this.wirelessPrice = wirelessPrice;
    }

    public Date getSaleBegin() {
        return saleBegin;
    }

    public void setSaleBegin(Date saleBegin) {
        this.saleBegin = saleBegin;
    }

    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public String getBarCode() {
        return barCode;
    }

    public void setBarCode(String barCode) {
        this.barCode = barCode;
    }

    public Long getSalesVolume() {
        return salesVolume;
    }

    public void setSalesVolume(Long salesVolume) {
        this.salesVolume = salesVolume;
    }

    public Long getComments() {
        return comments;
    }

    public void setComments(Long comments) {
        this.comments = comments;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.item_type
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    private Integer itemType;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.delete_mark
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    private Integer deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.gmt_created
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.gmt_modified
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shop_item.biz_code
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    private String bizCode;

    private Long itemId;


    private String itemName;

    private Long sellerId;
    private Long categoryId;
    private Long brandId;
    private String iconUrl;
    private Long marketPrice;
    private Long promotionPrice;
    private Long wirelessPrice;
    private Date saleBegin;
    // 商品类目名称条形码
    private String categoryName;
    private String barCode;
    private Long salesVolume;
    private Long comments;

    public Long getItemId() {
        return itemId;
    }

    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_name
     *
     * @return the value of shop_item.item_name
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_name
     *
     * @param itemName the value for shop_item.item_name
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.shop_id
     *
     * @return the value of shop_item.shop_id
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.shop_id
     *
     * @param shopId the value for shop_item.shop_id
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.seller_id
     *
     * @return the value of shop_item.seller_id
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.seller_id
     *
     * @param sellerId the value for shop_item.seller_id
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.item_type
     *
     * @return the value of shop_item.item_type
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.item_type
     *
     * @param itemType the value for shop_item.item_type
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.icon_url
     *
     * @return the value of shop_item.icon_url
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.icon_url
     *
     * @param iconUrl the value for shop_item.icon_url
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.delete_mark
     *
     * @return the value of shop_item.delete_mark
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public Integer getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.delete_mark
     *
     * @param deleteMark the value for shop_item.delete_mark
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setDeleteMark(Integer deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.gmt_created
     *
     * @return the value of shop_item.gmt_created
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.gmt_created
     *
     * @param gmtCreated the value for shop_item.gmt_created
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.gmt_modified
     *
     * @return the value of shop_item.gmt_modified
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.gmt_modified
     *
     * @param gmtModified the value for shop_item.gmt_modified
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shop_item.biz_code
     *
     * @return the value of shop_item.biz_code
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shop_item.biz_code
     *
     * @param bizCode the value for shop_item.biz_code
     *
     * @mbggenerated Tue Jan 12 14:54:30 CST 2016
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }
}