package com.mockuai.itemcenter.common.domain.dto;

import java.io.Serializable;
import java.util.Date;

public class ItemDescTmplDTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.id
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.seller_id
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private Long sellerId;

    private Long itemCount;


    public Long getItemCount() {
        return itemCount;
    }

    public void setItemCount(Long itemCount) {
        this.itemCount = itemCount;
    }

    private String tmsId;

    public String getTmsId() {
        return tmsId;
    }

    public void setTmsId(String tmsId) {
        this.tmsId = tmsId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.biz_code
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.delete_mark
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private Byte deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.gmt_created
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.gmt_modified
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.tmpl_name
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private String tmplName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.before_desc
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private String beforeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_desc_tmpl.after_desc
     *
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    private String afterDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.id
     *
     * @return the value of item_desc_tmpl.id
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.id
     *
     * @param id the value for item_desc_tmpl.id
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.seller_id
     *
     * @return the value of item_desc_tmpl.seller_id
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.seller_id
     *
     * @param sellerId the value for item_desc_tmpl.seller_id
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.biz_code
     *
     * @return the value of item_desc_tmpl.biz_code
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.biz_code
     *
     * @param bizCode the value for item_desc_tmpl.biz_code
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.delete_mark
     *
     * @return the value of item_desc_tmpl.delete_mark
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public Byte getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.delete_mark
     *
     * @param deleteMark the value for item_desc_tmpl.delete_mark
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setDeleteMark(Byte deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.gmt_created
     *
     * @return the value of item_desc_tmpl.gmt_created
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.gmt_created
     *
     * @param gmtCreated the value for item_desc_tmpl.gmt_created
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.gmt_modified
     *
     * @return the value of item_desc_tmpl.gmt_modified
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.gmt_modified
     *
     * @param gmtModified the value for item_desc_tmpl.gmt_modified
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.tmpl_name
     *
     * @return the value of item_desc_tmpl.tmpl_name
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public String getTmplName() {
        return tmplName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.tmpl_name
     *
     * @param tmplName the value for item_desc_tmpl.tmpl_name
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setTmplName(String tmplName) {
        this.tmplName = tmplName == null ? null : tmplName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.before_desc
     *
     * @return the value of item_desc_tmpl.before_desc
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public String getBeforeDesc() {
        return beforeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.before_desc
     *
     * @param beforeDesc the value for item_desc_tmpl.before_desc
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setBeforeDesc(String beforeDesc) {
        this.beforeDesc = beforeDesc == null ? null : beforeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_desc_tmpl.after_desc
     *
     * @return the value of item_desc_tmpl.after_desc
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public String getAfterDesc() {
        return afterDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_desc_tmpl.after_desc
     *
     * @param afterDesc the value for item_desc_tmpl.after_desc
     * @mbggenerated Fri Mar 04 14:58:55 CST 2016
     */
    public void setAfterDesc(String afterDesc) {
        this.afterDesc = afterDesc == null ? null : afterDesc.trim();
    }
}