package com.mockuai.itemcenter.common.domain.dto;

import java.io.Serializable;
import java.util.Date;

public class ItemSkuPropertyRecommendationDTO implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sku_property_recommendation.id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sku_property_recommendation.seller_id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    private Long sellerId;

    public void setBizCode(String bizCode) {
        this.bizCode = bizCode;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sku_property_recommendation.biz_code
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sku_property_recommendation.property_name
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    private String propertyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sku_property_recommendation.delete_mark
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    private Integer deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sku_property_recommendation.gmt_created
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sku_property_recommendation.gmt_modified
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_sku_property_recommendation.parent_id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sku_property_recommendation.id
     *
     * @return the value of item_sku_property_recommendation.id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sku_property_recommendation.id
     *
     * @param id the value for item_sku_property_recommendation.id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sku_property_recommendation.seller_id
     *
     * @return the value of item_sku_property_recommendation.seller_id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sku_property_recommendation.seller_id
     *
     * @param sellerId the value for item_sku_property_recommendation.seller_id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sku_property_recommendation.property_name
     *
     * @return the value of item_sku_property_recommendation.property_name
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sku_property_recommendation.property_name
     *
     * @param propertyName the value for item_sku_property_recommendation.property_name
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sku_property_recommendation.delete_mark
     *
     * @return the value of item_sku_property_recommendation.delete_mark
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public Integer getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sku_property_recommendation.delete_mark
     *
     * @param deleteMark the value for item_sku_property_recommendation.delete_mark
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public void setDeleteMark(Integer deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sku_property_recommendation.gmt_created
     *
     * @return the value of item_sku_property_recommendation.gmt_created
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sku_property_recommendation.gmt_created
     *
     * @param gmtCreated the value for item_sku_property_recommendation.gmt_created
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sku_property_recommendation.gmt_modified
     *
     * @return the value of item_sku_property_recommendation.gmt_modified
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sku_property_recommendation.gmt_modified
     *
     * @param gmtModified the value for item_sku_property_recommendation.gmt_modified
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_sku_property_recommendation.parent_id
     *
     * @return the value of item_sku_property_recommendation.parent_id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_sku_property_recommendation.parent_id
     *
     * @param parentId the value for item_sku_property_recommendation.parent_id
     *
     * @mbggenerated Mon Jan 11 09:06:20 CST 2016
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}