package com.mockuai.itemcenter.common.domain.dto;

import java.io.Serializable;
import java.util.Date;

public class RItemServiceTypeDTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_service_type.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_service_type.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_service_type.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_service_type.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Byte deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_service_type.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_service_type.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_service_type.type_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_service_type.item_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_service_type.id
     *
     * @return the value of r_item_service_type.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_service_type.id
     *
     * @param id the value for r_item_service_type.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_service_type.seller_id
     *
     * @return the value of r_item_service_type.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_service_type.seller_id
     *
     * @param sellerId the value for r_item_service_type.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_service_type.biz_code
     *
     * @return the value of r_item_service_type.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_service_type.biz_code
     *
     * @param bizCode the value for r_item_service_type.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_service_type.delete_mark
     *
     * @return the value of r_item_service_type.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Byte getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_service_type.delete_mark
     *
     * @param deleteMark the value for r_item_service_type.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setDeleteMark(Byte deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_service_type.gmt_created
     *
     * @return the value of r_item_service_type.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_service_type.gmt_created
     *
     * @param gmtCreated the value for r_item_service_type.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_service_type.gmt_modified
     *
     * @return the value of r_item_service_type.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_service_type.gmt_modified
     *
     * @param gmtModified the value for r_item_service_type.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_service_type.type_id
     *
     * @return the value of r_item_service_type.type_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_service_type.type_id
     *
     * @param typeId the value for r_item_service_type.type_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_service_type.item_id
     *
     * @return the value of r_item_service_type.item_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_service_type.item_id
     *
     * @param itemId the value for r_item_service_type.item_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }
}