package com.mockuai.itemcenter.common.domain.dto;

import java.io.Serializable;
import java.util.Date;

public class SupplierDTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.id
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.name
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contact_name
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private String contactName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contact_phone
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.level
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.type
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.seller_id
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.gmt_created
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.gmt_modified
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.biz_code
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.delete_mark
     *
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    private Byte deleteMark;

    private String merchantCustomsCode;

    private String merchantCustomsName;

    private String customsPlace;

    public String getMerchantCustomsCode() {
        return merchantCustomsCode;
    }

    public void setMerchantCustomsCode(String merchantCustomsCode) {
        this.merchantCustomsCode = merchantCustomsCode;
    }

    public String getMerchantCustomsName() {
        return merchantCustomsName;
    }

    public void setMerchantCustomsName(String merchantCustomsName) {
        this.merchantCustomsName = merchantCustomsName;
    }

    public String getCustomsPlace() {
        return customsPlace;
    }

    public void setCustomsPlace(String customsPlace) {
        this.customsPlace = customsPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.id
     *
     * @return the value of supplier.id
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.id
     *
     * @param id the value for supplier.id
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.name
     *
     * @return the value of supplier.name
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.name
     *
     * @param name the value for supplier.name
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contact_name
     *
     * @return the value of supplier.contact_name
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contact_name
     *
     * @param contactName the value for supplier.contact_name
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contact_phone
     *
     * @return the value of supplier.contact_phone
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contact_phone
     *
     * @param contactPhone the value for supplier.contact_phone
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.level
     *
     * @return the value of supplier.level
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.level
     *
     * @param Level the value for supplier.level
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setLevel(String Level) {
        this.level = level == null ? null : Level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.type
     *
     * @return the value of supplier.type
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.type
     *
     * @param type the value for supplier.type
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.seller_id
     *
     * @return the value of supplier.seller_id
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.seller_id
     *
     * @param sellerId the value for supplier.seller_id
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.gmt_created
     *
     * @return the value of supplier.gmt_created
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.gmt_created
     *
     * @param gmtCreated the value for supplier.gmt_created
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.gmt_modified
     *
     * @return the value of supplier.gmt_modified
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.gmt_modified
     *
     * @param gmtModified the value for supplier.gmt_modified
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.biz_code
     *
     * @return the value of supplier.biz_code
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.biz_code
     *
     * @param bizCode the value for supplier.biz_code
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.delete_mark
     *
     * @return the value of supplier.delete_mark
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public Byte getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.delete_mark
     *
     * @param deleteMark the value for supplier.delete_mark
     * @mbggenerated Mon Mar 21 10:20:06 CST 2016
     */
    public void setDeleteMark(Byte deleteMark) {
        this.deleteMark = deleteMark;
    }
}