package com.mockuai.itemcenter.common.domain.dto;

import java.io.Serializable;
import java.util.Date;

public class ValueAddedServiceDTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Byte deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.type_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.service_name
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String serviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.service_desc
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String serviceDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.icon_url
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column value_added_service.service_price
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long servicePrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.id
     *
     * @return the value of value_added_service.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.id
     *
     * @param id the value for value_added_service.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.seller_id
     *
     * @return the value of value_added_service.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.seller_id
     *
     * @param sellerId the value for value_added_service.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.biz_code
     *
     * @return the value of value_added_service.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.biz_code
     *
     * @param bizCode the value for value_added_service.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.delete_mark
     *
     * @return the value of value_added_service.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Byte getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.delete_mark
     *
     * @param deleteMark the value for value_added_service.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setDeleteMark(Byte deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.gmt_created
     *
     * @return the value of value_added_service.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.gmt_created
     *
     * @param gmtCreated the value for value_added_service.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.gmt_modified
     *
     * @return the value of value_added_service.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.gmt_modified
     *
     * @param gmtModified the value for value_added_service.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.type_id
     *
     * @return the value of value_added_service.type_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.type_id
     *
     * @param typeId the value for value_added_service.type_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.service_name
     *
     * @return the value of value_added_service.service_name
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.service_name
     *
     * @param serviceName the value for value_added_service.service_name
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName == null ? null : serviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.service_desc
     *
     * @return the value of value_added_service.service_desc
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getServiceDesc() {
        return serviceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.service_desc
     *
     * @param serviceDesc the value for value_added_service.service_desc
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setServiceDesc(String serviceDesc) {
        this.serviceDesc = serviceDesc == null ? null : serviceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.icon_url
     *
     * @return the value of value_added_service.icon_url
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.icon_url
     *
     * @param iconUrl the value for value_added_service.icon_url
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column value_added_service.service_price
     *
     * @return the value of value_added_service.service_price
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getServicePrice() {
        return servicePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column value_added_service.service_price
     *
     * @param servicePrice the value for value_added_service.service_price
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setServicePrice(Long servicePrice) {
        this.servicePrice = servicePrice;
    }
}