package com.mockuai.itemcenter.core.dao;

import com.mockuai.itemcenter.core.domain.RItemShopDO;

public interface RItemShopDODAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    void insert(RItemShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    void insertSelective(RItemShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    RItemShopDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    int updateByPrimaryKeySelective(RItemShopDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    int updateByPrimaryKey(RItemShopDO record);
}