package com.mockuai.itemcenter.common.domain.qto;

import com.mockuai.itemcenter.common.page.PageInfo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class ItemSettlementConditionQTO extends PageInfo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_condition.id
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_condition.biz_code
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    private String bizCode;


    private Long parentId;

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_condition.min_price
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    private Long minPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_condition.max_price
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    private Long maxPrice;

    private List<Long> idList;

    public List<Long> getIdList() {
        return idList;
    }

    public void setIdList(List<Long> idList) {
        this.idList = idList;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_condition.commission_ratio
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    private Integer commissionRatio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_condition.delete_mark
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    private Integer deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_condition.gmt_created
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_condition.gmt_modified
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_condition.id
     *
     * @return the value of item_settlement_condition.id
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_condition.id
     *
     * @param id the value for item_settlement_condition.id
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_condition.biz_code
     *
     * @return the value of item_settlement_condition.biz_code
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_condition.biz_code
     *
     * @param bizCode the value for item_settlement_condition.biz_code
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_condition.min_price
     *
     * @return the value of item_settlement_condition.min_price
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public Long getMinPrice() {
        return minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_condition.min_price
     *
     * @param minPrice the value for item_settlement_condition.min_price
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void setMinPrice(Long minPrice) {
        this.minPrice = minPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_condition.max_price
     *
     * @return the value of item_settlement_condition.max_price
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public Long getMaxPrice() {
        return maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_condition.max_price
     *
     * @param maxPrice the value for item_settlement_condition.max_price
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void setMaxPrice(Long maxPrice) {
        this.maxPrice = maxPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_condition.commission_ratio
     *
     * @return the value of item_settlement_condition.commission_ratio
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public Integer getCommissionRatio() {
        return commissionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_condition.commission_ratio
     *
     * @param commissionRatio the value for item_settlement_condition.commission_ratio
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void setCommissionRatio(Integer commissionRatio) {
        this.commissionRatio = commissionRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_condition.delete_mark
     *
     * @return the value of item_settlement_condition.delete_mark
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public Integer getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_condition.delete_mark
     *
     * @param deleteMark the value for item_settlement_condition.delete_mark
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void setDeleteMark(Integer deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_condition.gmt_created
     *
     * @return the value of item_settlement_condition.gmt_created
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_condition.gmt_created
     *
     * @param gmtCreated the value for item_settlement_condition.gmt_created
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_condition.gmt_modified
     *
     * @return the value of item_settlement_condition.gmt_modified
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_condition.gmt_modified
     *
     * @param gmtModified the value for item_settlement_condition.gmt_modified
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}