package com.mockuai.itemcenter.common.domain.qto;

import java.io.Serializable;
import java.util.Date;

public class RItemLabelQTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_label.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_label.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_label.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_label.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Byte deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_label.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_label.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_label.item_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_label.label_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long labelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_label.id
     *
     * @return the value of r_item_label.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_label.id
     *
     * @param id the value for r_item_label.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_label.seller_id
     *
     * @return the value of r_item_label.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_label.seller_id
     *
     * @param sellerId the value for r_item_label.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_label.biz_code
     *
     * @return the value of r_item_label.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_label.biz_code
     *
     * @param bizCode the value for r_item_label.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_label.delete_mark
     *
     * @return the value of r_item_label.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Byte getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_label.delete_mark
     *
     * @param deleteMark the value for r_item_label.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setDeleteMark(Byte deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_label.gmt_created
     *
     * @return the value of r_item_label.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_label.gmt_created
     *
     * @param gmtCreated the value for r_item_label.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_label.gmt_modified
     *
     * @return the value of r_item_label.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_label.gmt_modified
     *
     * @param gmtModified the value for r_item_label.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_label.item_id
     *
     * @return the value of r_item_label.item_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_label.item_id
     *
     * @param itemId the value for r_item_label.item_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_label.label_id
     *
     * @return the value of r_item_label.label_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_label.label_id
     *
     * @param labelId the value for r_item_label.label_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }
}