package com.mockuai.itemcenter.common.domain.qto;

import java.io.Serializable;
import java.util.Date;

public class RItemSuitQTO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.seller_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.biz_code
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.delete_mark
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Byte deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.gmt_created
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.gmt_modified
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.suit_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Long suitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.suit_sku_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Long suitSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.sub_item_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Long subItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.sub_item_sku_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private Long subItemSkuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.sub_item_name
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private String subItemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_item_suit.sub_item_icon
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    private String subItemIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.id
     *
     * @return the value of r_item_suit.id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.id
     *
     * @param id the value for r_item_suit.id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.seller_id
     *
     * @return the value of r_item_suit.seller_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.seller_id
     *
     * @param sellerId the value for r_item_suit.seller_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.biz_code
     *
     * @return the value of r_item_suit.biz_code
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.biz_code
     *
     * @param bizCode the value for r_item_suit.biz_code
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.delete_mark
     *
     * @return the value of r_item_suit.delete_mark
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Byte getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.delete_mark
     *
     * @param deleteMark the value for r_item_suit.delete_mark
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setDeleteMark(Byte deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.gmt_created
     *
     * @return the value of r_item_suit.gmt_created
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.gmt_created
     *
     * @param gmtCreated the value for r_item_suit.gmt_created
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.gmt_modified
     *
     * @return the value of r_item_suit.gmt_modified
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.gmt_modified
     *
     * @param gmtModified the value for r_item_suit.gmt_modified
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.suit_id
     *
     * @return the value of r_item_suit.suit_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Long getSuitId() {
        return suitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.suit_id
     *
     * @param suitId the value for r_item_suit.suit_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setSuitId(Long suitId) {
        this.suitId = suitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.suit_sku_id
     *
     * @return the value of r_item_suit.suit_sku_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Long getSuitSkuId() {
        return suitSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.suit_sku_id
     *
     * @param suitSkuId the value for r_item_suit.suit_sku_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setSuitSkuId(Long suitSkuId) {
        this.suitSkuId = suitSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.sub_item_id
     *
     * @return the value of r_item_suit.sub_item_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Long getSubItemId() {
        return subItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.sub_item_id
     *
     * @param subItemId the value for r_item_suit.sub_item_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setSubItemId(Long subItemId) {
        this.subItemId = subItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.sub_item_sku_id
     *
     * @return the value of r_item_suit.sub_item_sku_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public Long getSubItemSkuId() {
        return subItemSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.sub_item_sku_id
     *
     * @param subItemSkuId the value for r_item_suit.sub_item_sku_id
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setSubItemSkuId(Long subItemSkuId) {
        this.subItemSkuId = subItemSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.sub_item_name
     *
     * @return the value of r_item_suit.sub_item_name
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public String getSubItemName() {
        return subItemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.sub_item_name
     *
     * @param subItemName the value for r_item_suit.sub_item_name
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setSubItemName(String subItemName) {
        this.subItemName = subItemName == null ? null : subItemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_item_suit.sub_item_icon
     *
     * @return the value of r_item_suit.sub_item_icon
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public String getSubItemIcon() {
        return subItemIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_item_suit.sub_item_icon
     *
     * @param subItemIcon the value for r_item_suit.sub_item_icon
     *
     * @mbggenerated Fri Dec 04 15:13:50 CST 2015
     */
    public void setSubItemIcon(String subItemIcon) {
        this.subItemIcon = subItemIcon == null ? null : subItemIcon.trim();
    }
}