package com.mockuai.itemcenter.core.domain;

import java.util.Date;

public class ItemLabelDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Integer deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.label_name
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.label_desc
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String labelDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.icon_url
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private String iconUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_label.scope
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    private Integer scope;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.id
     *
     * @return the value of item_label.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.id
     *
     * @param id the value for item_label.id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.seller_id
     *
     * @return the value of item_label.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.seller_id
     *
     * @param sellerId the value for item_label.seller_id
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.biz_code
     *
     * @return the value of item_label.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.biz_code
     *
     * @param bizCode the value for item_label.biz_code
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.delete_mark
     *
     * @return the value of item_label.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Integer getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.delete_mark
     *
     * @param deleteMark the value for item_label.delete_mark
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setDeleteMark(Integer deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.gmt_created
     *
     * @return the value of item_label.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.gmt_created
     *
     * @param gmtCreated the value for item_label.gmt_created
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.gmt_modified
     *
     * @return the value of item_label.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.gmt_modified
     *
     * @param gmtModified the value for item_label.gmt_modified
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.label_name
     *
     * @return the value of item_label.label_name
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.label_name
     *
     * @param labelName the value for item_label.label_name
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName == null ? null : labelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.label_desc
     *
     * @return the value of item_label.label_desc
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getLabelDesc() {
        return labelDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.label_desc
     *
     * @param labelDesc the value for item_label.label_desc
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setLabelDesc(String labelDesc) {
        this.labelDesc = labelDesc == null ? null : labelDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.icon_url
     *
     * @return the value of item_label.icon_url
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.icon_url
     *
     * @param iconUrl the value for item_label.icon_url
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_label.scope
     *
     * @return the value of item_label.scope
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public Integer getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_label.scope
     *
     * @param scope the value for item_label.scope
     *
     * @mbggenerated Thu Dec 03 21:37:40 CST 2015
     */
    public void setScope(Integer scope) {
        this.scope = scope;
    }
}