package com.mockuai.itemcenter.core.domain;

import java.util.Date;

public class ItemSettlementConfigDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_config.id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_config.biz_code
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_config.scope
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Integer scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_config.enable
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Integer enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_config.config_name
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_config.delete_mark
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Integer deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_config.gmt_created
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_settlement_config.gmt_modified
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_config.id
     *
     * @return the value of item_settlement_config.id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_config.id
     *
     * @param id the value for item_settlement_config.id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_config.biz_code
     *
     * @return the value of item_settlement_config.biz_code
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_config.biz_code
     *
     * @param bizCode the value for item_settlement_config.biz_code
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_config.scope
     *
     * @return the value of item_settlement_config.scope
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Integer getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_config.scope
     *
     * @param scope the value for item_settlement_config.scope
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setScope(Integer scope) {
        this.scope = scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_config.enable
     *
     * @return the value of item_settlement_config.enable
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Integer getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_config.enable
     *
     * @param enable the value for item_settlement_config.enable
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setEnable(Integer enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_config.config_name
     *
     * @return the value of item_settlement_config.config_name
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_config.config_name
     *
     * @param configName the value for item_settlement_config.config_name
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_config.delete_mark
     *
     * @return the value of item_settlement_config.delete_mark
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Integer getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_config.delete_mark
     *
     * @param deleteMark the value for item_settlement_config.delete_mark
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setDeleteMark(Integer deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_config.gmt_created
     *
     * @return the value of item_settlement_config.gmt_created
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_config.gmt_created
     *
     * @param gmtCreated the value for item_settlement_config.gmt_created
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_settlement_config.gmt_modified
     *
     * @return the value of item_settlement_config.gmt_modified
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_settlement_config.gmt_modified
     *
     * @param gmtModified the value for item_settlement_config.gmt_modified
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}