package com.mockuai.itemcenter.core.domain;

import java.util.Date;

public class RShopSettlementDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_shop_settlement.id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_shop_settlement.seller_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Long sellerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_shop_settlement.shop_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Long shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_shop_settlement.biz_code
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private String bizCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_shop_settlement.settlement_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Long settlementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_shop_settlement.delete_mark
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Integer deleteMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_shop_settlement.gmt_created
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_shop_settlement.gmt_modified
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_shop_settlement.id
     *
     * @return the value of r_shop_settlement.id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_shop_settlement.id
     *
     * @param id the value for r_shop_settlement.id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_shop_settlement.seller_id
     *
     * @return the value of r_shop_settlement.seller_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Long getSellerId() {
        return sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_shop_settlement.seller_id
     *
     * @param sellerId the value for r_shop_settlement.seller_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setSellerId(Long sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_shop_settlement.shop_id
     *
     * @return the value of r_shop_settlement.shop_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Long getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_shop_settlement.shop_id
     *
     * @param shopId the value for r_shop_settlement.shop_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setShopId(Long shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_shop_settlement.biz_code
     *
     * @return the value of r_shop_settlement.biz_code
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_shop_settlement.biz_code
     *
     * @param bizCode the value for r_shop_settlement.biz_code
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_shop_settlement.settlement_id
     *
     * @return the value of r_shop_settlement.settlement_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Long getSettlementId() {
        return settlementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_shop_settlement.settlement_id
     *
     * @param settlementId the value for r_shop_settlement.settlement_id
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setSettlementId(Long settlementId) {
        this.settlementId = settlementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_shop_settlement.delete_mark
     *
     * @return the value of r_shop_settlement.delete_mark
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Integer getDeleteMark() {
        return deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_shop_settlement.delete_mark
     *
     * @param deleteMark the value for r_shop_settlement.delete_mark
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setDeleteMark(Integer deleteMark) {
        this.deleteMark = deleteMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_shop_settlement.gmt_created
     *
     * @return the value of r_shop_settlement.gmt_created
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_shop_settlement.gmt_created
     *
     * @param gmtCreated the value for r_shop_settlement.gmt_created
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_shop_settlement.gmt_modified
     *
     * @return the value of r_shop_settlement.gmt_modified
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_shop_settlement.gmt_modified
     *
     * @param gmtModified the value for r_shop_settlement.gmt_modified
     *
     * @mbggenerated Tue Jan 19 10:06:45 CST 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}