package com.mockuai.marketingcenter.core.dao.impl;

import com.mockuai.marketingcenter.core.domain.OrderDetailDO;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OrderDetailDAOImpl extends SqlMapClientDaoSupport implements OrderDetailDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Mon Jul 18 15:38:18 CST 2016
     */
    public OrderDetailDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Mon Jul 18 15:38:18 CST 2016
     */
    public int deleteByPrimaryKey(Long id) {
        OrderDetailDO _key = new OrderDetailDO();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("order_detail.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Mon Jul 18 15:38:18 CST 2016
     */
    public void insert(OrderDetailDO record) {
        getSqlMapClientTemplate().insert("order_detail.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Mon Jul 18 15:38:18 CST 2016
     */
    public void insertSelective(OrderDetailDO record) {
        getSqlMapClientTemplate().insert("order_detail.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Mon Jul 18 15:38:18 CST 2016
     */
    public OrderDetailDO selectByPrimaryKey(Long id) {
        OrderDetailDO _key = new OrderDetailDO();
        _key.setId(id);
        OrderDetailDO record = (OrderDetailDO) getSqlMapClientTemplate().queryForObject("order_detail.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Mon Jul 18 15:38:18 CST 2016
     */
    public int updateByPrimaryKeySelective(OrderDetailDO record) {
        int rows = getSqlMapClientTemplate().update("order_detail.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_detail
     *
     * @mbggenerated Mon Jul 18 15:38:18 CST 2016
     */
    public int updateByPrimaryKey(OrderDetailDO record) {
        int rows = getSqlMapClientTemplate().update("order_detail.updateByPrimaryKey", record);
        return rows;
    }
}