package com.mockuai.itemcenter.core.dao.impl;

import com.mockuai.itemcenter.core.dao.RItemShopDODAO;
import com.mockuai.itemcenter.core.domain.RItemShopDO;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class RItemShopDAOImpl extends SqlMapClientDaoSupport implements RItemShopDODAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public RItemShopDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public int deleteByPrimaryKey(Long id) {
        RItemShopDO _key = new RItemShopDO();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("r_shop_label.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void insert(RItemShopDO record) {
        getSqlMapClientTemplate().insert("r_shop_label.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public void insertSelective(RItemShopDO record) {
        getSqlMapClientTemplate().insert("r_shop_label.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public RItemShopDO selectByPrimaryKey(Long id) {
        RItemShopDO _key = new RItemShopDO();
        _key.setId(id);
        RItemShopDO record = (RItemShopDO) getSqlMapClientTemplate().queryForObject("r_shop_label.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public int updateByPrimaryKeySelective(RItemShopDO record) {
        int rows = getSqlMapClientTemplate().update("r_shop_label.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_shop_label
     *
     * @mbggenerated Mon Jan 11 16:57:47 CST 2016
     */
    public int updateByPrimaryKey(RItemShopDO record) {
        int rows = getSqlMapClientTemplate().update("r_shop_label.updateByPrimaryKey", record);
        return rows;
    }
}